// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _binary_threshold_HH_
#define _binary_threshold_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "binary_threshold_AXILiteS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_AXILITES_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_AXILITES_DATA_WIDTH = 32>
struct binary_threshold : public sc_module {
    // Port declarations 37
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_lv<32> > input_image_TDATA;
    sc_in< sc_logic > input_image_TVALID;
    sc_out< sc_logic > input_image_TREADY;
    sc_in< sc_lv<4> > input_image_TKEEP;
    sc_in< sc_lv<4> > input_image_TSTRB;
    sc_in< sc_lv<2> > input_image_TUSER;
    sc_in< sc_lv<1> > input_image_TLAST;
    sc_in< sc_lv<5> > input_image_TID;
    sc_in< sc_lv<6> > input_image_TDEST;
    sc_out< sc_lv<32> > output_image_TDATA;
    sc_out< sc_logic > output_image_TVALID;
    sc_in< sc_logic > output_image_TREADY;
    sc_out< sc_lv<4> > output_image_TKEEP;
    sc_out< sc_lv<4> > output_image_TSTRB;
    sc_out< sc_lv<2> > output_image_TUSER;
    sc_out< sc_lv<1> > output_image_TLAST;
    sc_out< sc_lv<5> > output_image_TID;
    sc_out< sc_lv<6> > output_image_TDEST;
    sc_in< sc_logic > s_axi_AXILiteS_AWVALID;
    sc_out< sc_logic > s_axi_AXILiteS_AWREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_AWADDR;
    sc_in< sc_logic > s_axi_AXILiteS_WVALID;
    sc_out< sc_logic > s_axi_AXILiteS_WREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_WDATA;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH/8> > s_axi_AXILiteS_WSTRB;
    sc_in< sc_logic > s_axi_AXILiteS_ARVALID;
    sc_out< sc_logic > s_axi_AXILiteS_ARREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_ARADDR;
    sc_out< sc_logic > s_axi_AXILiteS_RVALID;
    sc_in< sc_logic > s_axi_AXILiteS_RREADY;
    sc_out< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_RDATA;
    sc_out< sc_lv<2> > s_axi_AXILiteS_RRESP;
    sc_out< sc_logic > s_axi_AXILiteS_BVALID;
    sc_in< sc_logic > s_axi_AXILiteS_BREADY;
    sc_out< sc_lv<2> > s_axi_AXILiteS_BRESP;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    binary_threshold(sc_module_name name);
    SC_HAS_PROCESS(binary_threshold);

    ~binary_threshold();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    binary_threshold_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>* binary_threshold_AXILiteS_s_axi_U;
    regslice_both<32>* regslice_both_input_image_data_V_U;
    regslice_both<4>* regslice_both_input_image_keep_V_U;
    regslice_both<4>* regslice_both_input_image_strb_V_U;
    regslice_both<2>* regslice_both_input_image_user_V_U;
    regslice_both<1>* regslice_both_input_image_last_V_U;
    regslice_both<5>* regslice_both_input_image_id_V_U;
    regslice_both<6>* regslice_both_input_image_dest_V_U;
    regslice_both<32>* regslice_both_output_image_data_V_U;
    regslice_both<4>* regslice_both_output_image_keep_V_U;
    regslice_both<4>* regslice_both_output_image_strb_V_U;
    regslice_both<2>* regslice_both_output_image_user_V_U;
    regslice_both<1>* regslice_both_output_image_last_V_U;
    regslice_both<5>* regslice_both_output_image_id_V_U;
    regslice_both<6>* regslice_both_output_image_dest_V_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<32> > length_V;
    sc_signal< sc_lv<32> > length_V_0_data_reg;
    sc_signal< sc_logic > length_V_0_vld_reg;
    sc_signal< sc_logic > length_V_0_ack_out;
    sc_signal< sc_lv<32> > threshold_V;
    sc_signal< sc_lv<32> > threshold_V_0_data_reg;
    sc_signal< sc_logic > threshold_V_0_vld_reg;
    sc_signal< sc_logic > threshold_V_0_ack_out;
    sc_signal< sc_lv<32> > max_val_V;
    sc_signal< sc_lv<32> > max_val_V_0_data_reg;
    sc_signal< sc_logic > max_val_V_0_vld_reg;
    sc_signal< sc_logic > max_val_V_0_ack_out;
    sc_signal< sc_logic > input_image_TDATA_blk_n;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > icmp_ln46_fu_150_p2;
    sc_signal< sc_logic > output_image_TDATA_blk_n;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_lv<1> > icmp_ln46_reg_220;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_lv<1> > icmp_ln46_reg_220_pp0_iter1_reg;
    sc_signal< sc_lv<32> > i_op_assign_reg_133;
    sc_signal< sc_lv<32> > max_val_V_read_reg_201;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<32> > threshold_V_read_reg_206;
    sc_signal< sc_lv<32> > length_V_read_reg_211;
    sc_signal< sc_lv<1> > icmp_ln895_fu_144_p2;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state4_io;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state5_io;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<32> > i_fu_155_p2;
    sc_signal< sc_lv<4> > input_image_keep_V_t_reg_229;
    sc_signal< sc_lv<4> > input_image_strb_V_t_reg_234;
    sc_signal< sc_lv<2> > input_image_user_V_t_reg_239;
    sc_signal< sc_lv<1> > input_image_last_V_t_reg_244;
    sc_signal< sc_lv<5> > input_image_id_V_tmp_reg_249;
    sc_signal< sc_lv<6> > input_image_dest_V_t_reg_254;
    sc_signal< sc_lv<1> > icmp_ln895_1_fu_189_p2;
    sc_signal< sc_lv<1> > icmp_ln895_1_reg_259;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state3;
    sc_signal< bool > ap_block_pp0_stage0_01001;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_logic > regslice_both_output_image_data_V_U_apdone_blk;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    sc_signal< sc_logic > regslice_both_input_image_data_V_U_apdone_blk;
    sc_signal< sc_lv<32> > input_image_TDATA_int;
    sc_signal< sc_logic > input_image_TVALID_int;
    sc_signal< sc_logic > input_image_TREADY_int;
    sc_signal< sc_logic > regslice_both_input_image_data_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_input_image_keep_V_U_apdone_blk;
    sc_signal< sc_lv<4> > input_image_TKEEP_int;
    sc_signal< sc_logic > regslice_both_input_image_keep_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_input_image_keep_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_input_image_strb_V_U_apdone_blk;
    sc_signal< sc_lv<4> > input_image_TSTRB_int;
    sc_signal< sc_logic > regslice_both_input_image_strb_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_input_image_strb_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_input_image_user_V_U_apdone_blk;
    sc_signal< sc_lv<2> > input_image_TUSER_int;
    sc_signal< sc_logic > regslice_both_input_image_user_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_input_image_user_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_input_image_last_V_U_apdone_blk;
    sc_signal< sc_lv<1> > input_image_TLAST_int;
    sc_signal< sc_logic > regslice_both_input_image_last_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_input_image_last_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_input_image_id_V_U_apdone_blk;
    sc_signal< sc_lv<5> > input_image_TID_int;
    sc_signal< sc_logic > regslice_both_input_image_id_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_input_image_id_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_input_image_dest_V_U_apdone_blk;
    sc_signal< sc_lv<6> > input_image_TDEST_int;
    sc_signal< sc_logic > regslice_both_input_image_dest_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_input_image_dest_V_U_ack_in;
    sc_signal< sc_lv<32> > output_image_TDATA_int;
    sc_signal< sc_logic > output_image_TVALID_int;
    sc_signal< sc_logic > output_image_TREADY_int;
    sc_signal< sc_logic > regslice_both_output_image_data_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_output_image_keep_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_output_image_keep_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_output_image_keep_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_output_image_strb_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_output_image_strb_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_output_image_strb_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_output_image_user_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_output_image_user_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_output_image_user_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_output_image_last_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_output_image_last_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_output_image_last_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_output_image_id_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_output_image_id_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_output_image_id_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_output_image_dest_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_output_image_dest_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_output_image_dest_V_U_vld_out;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_state2;
    static const sc_lv<4> ap_ST_fsm_pp0_stage0;
    static const sc_lv<4> ap_ST_fsm_state6;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_3;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state6();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_01001();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state3_pp0_stage0_iter0();
    void thread_ap_block_state4_io();
    void thread_ap_block_state4_pp0_stage0_iter1();
    void thread_ap_block_state5_io();
    void thread_ap_block_state5_pp0_stage0_iter2();
    void thread_ap_condition_pp0_exit_iter0_state3();
    void thread_ap_enable_pp0();
    void thread_ap_idle_pp0();
    void thread_ap_rst_n_inv();
    void thread_i_fu_155_p2();
    void thread_icmp_ln46_fu_150_p2();
    void thread_icmp_ln895_1_fu_189_p2();
    void thread_icmp_ln895_fu_144_p2();
    void thread_input_image_TDATA_blk_n();
    void thread_input_image_TREADY();
    void thread_input_image_TREADY_int();
    void thread_length_V_0_ack_out();
    void thread_max_val_V_0_ack_out();
    void thread_output_image_TDATA_blk_n();
    void thread_output_image_TDATA_int();
    void thread_output_image_TVALID();
    void thread_output_image_TVALID_int();
    void thread_threshold_V_0_ack_out();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
